from os.path import splitext

tests = glob([
  '*.cpp',
])

for test in tests:
  cxx_test(
    name = splitext(test)[0],
    srcs = [
      test
    ],
    deps = [
      '//utils/unittest/googletest:gtest',
      '//utils/unittest/UnitTestMain:UnitTestMain',
      '//:support',
      '//:adt',
      '//:ir',
    ],
  )
