cxx_binary(
  name = 'HowToUseJIT',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:llvm',
  ],
)
