cxx_binary(
  name = 'BrainF',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  linker_flags = [
    '-ldl',
  ],
  deps = [
    '//:ir',
    '//:passes',
    '//:bitcode',
    '//:codegen',
    '//:executionengine',
    '//:x86',
  ],
)
