prebuilt_cxx_library(
  name = 'dl',
  header_only = True,
  exported_linker_flags = [
    '-ldl',
  ],
)

cxx_binary(
  name = 'BrainF',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  linker_flags = [
    '-ldl',
  ],
  deps = [
    '//:ir',
    '//:passes',
    '//:bitcode',
    '//:codegen',
    '//:executionengine',
    '//:x86',
    # '//:llvm',
    # ':dl',
  ],
)
