cxx_binary(
  name = 'ExceptionDemo',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  linker_flags = [
    '-ldl',
    '-lz',
    '-lncurses',
  ],
  deps = [
    '//:llvm',
    '//:x86',
  ],
)
